{"level":"error","time":"2023-04-20T01:23:23+08:00","message":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connect: connection refused"}
{"level":"error","time":"2023-04-20T01:23:25+08:00","message":"Failed to write server state data: UNKNOWN: redis command error: SADD failed: dial tcp 127.0.0.1:6379: connect: connection refused"}
{"level":"error","time":"2023-04-20T01:23:25+08:00","message":"Failed to delete expired completed tasks from queue \"high\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connect: connection refused"}
{"level":"error","time":"2023-04-20T01:23:25+08:00","message":"Failed to forward scheduled tasks: INTERNAL_ERROR: INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connect: connection refused"}
{"level":"error","time":"2023-04-20T01:23:25+08:00","message":"Failed to delete expired completed tasks from queue \"default\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connect: connection refused"}
{"level":"error","time":"2023-04-20T01:23:25+08:00","message":"Failed to delete expired completed tasks from queue \"low\": INTERNAL_ERROR: redis eval error: dial tcp 127.0.0.1:6379: connect: connection refused"}
{"level":"error","time":"2023-04-20T01:23:27+08:00","message":"Dequeue error: UNKNOWN: redis eval error: dial tcp 127.0.0.1:6379: connect: connection refused"}
